// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: patient/v1/patient.proto

package patientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Patient represents a patient entity
type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyName    string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenNames    []string               `protobuf:"bytes,3,rep,name=given_names,json=givenNames,proto3" json:"given_names,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Telecom       []*Contact             `protobuf:"bytes,6,rep,name=telecom,proto3" json:"telecom,omitempty"`
	Address       *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_patient_v1_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{0}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *Patient) GetGivenNames() []string {
	if x != nil {
		return x.GivenNames
	}
	return nil
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Patient) GetTelecom() []*Contact {
	if x != nil {
		return x.Telecom
	}
	return nil
}

func (x *Patient) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Patient) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Contact represents contact information
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"` // phone, email, fax
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Use           string                 `protobuf:"bytes,3,opt,name=use,proto3" json:"use,omitempty"` // home, work, mobile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_patient_v1_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *Contact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Contact) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

// Address represents a physical address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          []string               `protobuf:"bytes,1,rep,name=line,proto3" json:"line,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_patient_v1_patient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// CreatePatientRequest represents a request to create a patient
type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// CreatePatientResponse represents a response from creating a patient
type CreatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientResponse) Reset() {
	*x = CreatePatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientResponse) ProtoMessage() {}

func (x *CreatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientResponse.ProtoReflect.Descriptor instead.
func (*CreatePatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// GetPatientRequest represents a request to get a patient
type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPatientResponse represents a response from getting a patient
type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{6}
}

func (x *GetPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// UpdatePatientRequest represents a request to update a patient
type UpdatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientRequest) Reset() {
	*x = UpdatePatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientRequest) ProtoMessage() {}

func (x *UpdatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// UpdatePatientResponse represents a response from updating a patient
type UpdatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientResponse) Reset() {
	*x = UpdatePatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientResponse) ProtoMessage() {}

func (x *UpdatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// ListPatientsRequest represents a request to list patients
type ListPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsRequest) Reset() {
	*x = ListPatientsRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsRequest) ProtoMessage() {}

func (x *ListPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsRequest.ProtoReflect.Descriptor instead.
func (*ListPatientsRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{9}
}

func (x *ListPatientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPatientsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListPatientsResponse represents a response from listing patients
type ListPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsResponse) Reset() {
	*x = ListPatientsResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsResponse) ProtoMessage() {}

func (x *ListPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsResponse.ProtoReflect.Descriptor instead.
func (*ListPatientsResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{10}
}

func (x *ListPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *ListPatientsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_patient_v1_patient_proto protoreflect.FileDescriptor

const file_patient_v1_patient_proto_rawDesc = "" +
	"\n" +
	"\x18patient/v1/patient.proto\x12\n" +
	"patient.v1\"\x88\x02\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName\x12\x1f\n" +
	"\vgiven_names\x18\x03 \x03(\tR\n" +
	"givenNames\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12-\n" +
	"\atelecom\x18\x06 \x03(\v2\x13.patient.v1.ContactR\atelecom\x12-\n" +
	"\aaddress\x18\a \x01(\v2\x13.patient.v1.AddressR\aaddress\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"I\n" +
	"\aContact\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03use\x18\x03 \x01(\tR\x03use\"\x82\x01\n" +
	"\aAddress\x12\x12\n" +
	"\x04line\x18\x01 \x03(\tR\x04line\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"E\n" +
	"\x14CreatePatientRequest\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"F\n" +
	"\x15CreatePatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"#\n" +
	"\x11GetPatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetPatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"E\n" +
	"\x14UpdatePatientRequest\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"F\n" +
	"\x15UpdatePatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"Q\n" +
	"\x13ListPatientsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\x14ListPatientsResponse\x12/\n" +
	"\bpatients\x18\x01 \x03(\v2\x13.patient.v1.PatientR\bpatients\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xdc\x02\n" +
	"\x0ePatientService\x12T\n" +
	"\rCreatePatient\x12 .patient.v1.CreatePatientRequest\x1a!.patient.v1.CreatePatientResponse\x12K\n" +
	"\n" +
	"GetPatient\x12\x1d.patient.v1.GetPatientRequest\x1a\x1e.patient.v1.GetPatientResponse\x12T\n" +
	"\rUpdatePatient\x12 .patient.v1.UpdatePatientRequest\x1a!.patient.v1.UpdatePatientResponse\x12Q\n" +
	"\fListPatients\x12\x1f.patient.v1.ListPatientsRequest\x1a .patient.v1.ListPatientsResponseB\xad\x01\n" +
	"\x0ecom.patient.v1B\fPatientProtoP\x01ZDgithub.com/Sotiris-Bekiaris/careflow-mini/proto/patient/v1;patientv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Patient.V1\xca\x02\n" +
	"Patient\\V1\xe2\x02\x16Patient\\V1\\GPBMetadata\xea\x02\vPatient::V1b\x06proto3"

var (
	file_patient_v1_patient_proto_rawDescOnce sync.Once
	file_patient_v1_patient_proto_rawDescData []byte
)

func file_patient_v1_patient_proto_rawDescGZIP() []byte {
	file_patient_v1_patient_proto_rawDescOnce.Do(func() {
		file_patient_v1_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_v1_patient_proto_rawDesc), len(file_patient_v1_patient_proto_rawDesc)))
	})
	return file_patient_v1_patient_proto_rawDescData
}

var file_patient_v1_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_patient_v1_patient_proto_goTypes = []any{
	(*Patient)(nil),               // 0: patient.v1.Patient
	(*Contact)(nil),               // 1: patient.v1.Contact
	(*Address)(nil),               // 2: patient.v1.Address
	(*CreatePatientRequest)(nil),  // 3: patient.v1.CreatePatientRequest
	(*CreatePatientResponse)(nil), // 4: patient.v1.CreatePatientResponse
	(*GetPatientRequest)(nil),     // 5: patient.v1.GetPatientRequest
	(*GetPatientResponse)(nil),    // 6: patient.v1.GetPatientResponse
	(*UpdatePatientRequest)(nil),  // 7: patient.v1.UpdatePatientRequest
	(*UpdatePatientResponse)(nil), // 8: patient.v1.UpdatePatientResponse
	(*ListPatientsRequest)(nil),   // 9: patient.v1.ListPatientsRequest
	(*ListPatientsResponse)(nil),  // 10: patient.v1.ListPatientsResponse
}
var file_patient_v1_patient_proto_depIdxs = []int32{
	1,  // 0: patient.v1.Patient.telecom:type_name -> patient.v1.Contact
	2,  // 1: patient.v1.Patient.address:type_name -> patient.v1.Address
	0,  // 2: patient.v1.CreatePatientRequest.patient:type_name -> patient.v1.Patient
	0,  // 3: patient.v1.CreatePatientResponse.patient:type_name -> patient.v1.Patient
	0,  // 4: patient.v1.GetPatientResponse.patient:type_name -> patient.v1.Patient
	0,  // 5: patient.v1.UpdatePatientRequest.patient:type_name -> patient.v1.Patient
	0,  // 6: patient.v1.UpdatePatientResponse.patient:type_name -> patient.v1.Patient
	0,  // 7: patient.v1.ListPatientsResponse.patients:type_name -> patient.v1.Patient
	3,  // 8: patient.v1.PatientService.CreatePatient:input_type -> patient.v1.CreatePatientRequest
	5,  // 9: patient.v1.PatientService.GetPatient:input_type -> patient.v1.GetPatientRequest
	7,  // 10: patient.v1.PatientService.UpdatePatient:input_type -> patient.v1.UpdatePatientRequest
	9,  // 11: patient.v1.PatientService.ListPatients:input_type -> patient.v1.ListPatientsRequest
	4,  // 12: patient.v1.PatientService.CreatePatient:output_type -> patient.v1.CreatePatientResponse
	6,  // 13: patient.v1.PatientService.GetPatient:output_type -> patient.v1.GetPatientResponse
	8,  // 14: patient.v1.PatientService.UpdatePatient:output_type -> patient.v1.UpdatePatientResponse
	10, // 15: patient.v1.PatientService.ListPatients:output_type -> patient.v1.ListPatientsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_patient_v1_patient_proto_init() }
func file_patient_v1_patient_proto_init() {
	if File_patient_v1_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_v1_patient_proto_rawDesc), len(file_patient_v1_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_v1_patient_proto_goTypes,
		DependencyIndexes: file_patient_v1_patient_proto_depIdxs,
		MessageInfos:      file_patient_v1_patient_proto_msgTypes,
	}.Build()
	File_patient_v1_patient_proto = out.File
	file_patient_v1_patient_proto_goTypes = nil
	file_patient_v1_patient_proto_depIdxs = nil
}
