// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: appointment/v1/appointment.proto

package appointmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Appointment represents an appointment entity
type Appointment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // proposed, pending, booked, arrived, fulfilled, cancelled
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PractitionerId string                 `protobuf:"bytes,4,opt,name=practitioner_id,json=practitionerId,proto3" json:"practitioner_id,omitempty"`
	Start          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	ServiceType    string                 `protobuf:"bytes,7,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Appointment) GetPractitionerId() string {
	if x != nil {
		return x.PractitionerId
	}
	return ""
}

func (x *Appointment) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Appointment) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Appointment) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Appointment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateAppointmentRequest represents a request to create an appointment
type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// CreateAppointmentResponse represents a response from creating an appointment
type CreateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentResponse) Reset() {
	*x = CreateAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentResponse) ProtoMessage() {}

func (x *CreateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// GetAppointmentRequest represents a request to get an appointment
type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAppointmentResponse represents a response from getting an appointment
type GetAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentResponse) Reset() {
	*x = GetAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentResponse) ProtoMessage() {}

func (x *GetAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// ListAppointmentsRequest represents a request to list appointments
type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppointmentsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListAppointmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAppointmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListAppointmentsResponse represents a response from listing appointments
type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

func (x *ListAppointmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateAppointmentRequest represents a request to update an appointment
type UpdateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentRequest) Reset() {
	*x = UpdateAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRequest) ProtoMessage() {}

func (x *UpdateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// UpdateAppointmentResponse represents a response from updating an appointment
type UpdateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentResponse) Reset() {
	*x = UpdateAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentResponse) ProtoMessage() {}

func (x *UpdateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// CancelAppointmentRequest represents a request to cancel an appointment
type CancelAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentRequest) Reset() {
	*x = CancelAppointmentRequest{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRequest) ProtoMessage() {}

func (x *CancelAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{9}
}

func (x *CancelAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelAppointmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelAppointmentResponse represents a response from cancelling an appointment
type CancelAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentResponse) Reset() {
	*x = CancelAppointmentResponse{}
	mi := &file_appointment_v1_appointment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentResponse) ProtoMessage() {}

func (x *CancelAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_v1_appointment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CancelAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_v1_appointment_proto_rawDescGZIP(), []int{10}
}

func (x *CancelAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_appointment_v1_appointment_proto protoreflect.FileDescriptor

const file_appointment_v1_appointment_proto_rawDesc = "" +
	"\n" +
	" appointment/v1/appointment.proto\x12\x0eappointment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12'\n" +
	"\x0fpractitioner_id\x18\x04 \x01(\tR\x0epractitionerId\x120\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12!\n" +
	"\fservice_type\x18\a \x01(\tR\vserviceType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"Y\n" +
	"\x18CreateAppointmentRequest\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"Z\n" +
	"\x19CreateAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x16GetAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"t\n" +
	"\x17ListAppointmentsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x18ListAppointmentsResponse\x12?\n" +
	"\fappointments\x18\x01 \x03(\v2\x1b.appointment.v1.AppointmentR\fappointments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Y\n" +
	"\x18UpdateAppointmentRequest\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"Z\n" +
	"\x19UpdateAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"B\n" +
	"\x18CancelAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Z\n" +
	"\x19CancelAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment2\x9a\x04\n" +
	"\x12AppointmentService\x12h\n" +
	"\x11CreateAppointment\x12(.appointment.v1.CreateAppointmentRequest\x1a).appointment.v1.CreateAppointmentResponse\x12_\n" +
	"\x0eGetAppointment\x12%.appointment.v1.GetAppointmentRequest\x1a&.appointment.v1.GetAppointmentResponse\x12e\n" +
	"\x10ListAppointments\x12'.appointment.v1.ListAppointmentsRequest\x1a(.appointment.v1.ListAppointmentsResponse\x12h\n" +
	"\x11UpdateAppointment\x12(.appointment.v1.UpdateAppointmentRequest\x1a).appointment.v1.UpdateAppointmentResponse\x12h\n" +
	"\x11CancelAppointment\x12(.appointment.v1.CancelAppointmentRequest\x1a).appointment.v1.CancelAppointmentResponseB\xcd\x01\n" +
	"\x12com.appointment.v1B\x10AppointmentProtoP\x01ZLgithub.com/Sotiris-Bekiaris/careflow-mini/proto/appointment/v1;appointmentv1\xa2\x02\x03AXX\xaa\x02\x0eAppointment.V1\xca\x02\x0eAppointment\\V1\xe2\x02\x1aAppointment\\V1\\GPBMetadata\xea\x02\x0fAppointment::V1b\x06proto3"

var (
	file_appointment_v1_appointment_proto_rawDescOnce sync.Once
	file_appointment_v1_appointment_proto_rawDescData []byte
)

func file_appointment_v1_appointment_proto_rawDescGZIP() []byte {
	file_appointment_v1_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_v1_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appointment_v1_appointment_proto_rawDesc), len(file_appointment_v1_appointment_proto_rawDesc)))
	})
	return file_appointment_v1_appointment_proto_rawDescData
}

var file_appointment_v1_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_appointment_v1_appointment_proto_goTypes = []any{
	(*Appointment)(nil),               // 0: appointment.v1.Appointment
	(*CreateAppointmentRequest)(nil),  // 1: appointment.v1.CreateAppointmentRequest
	(*CreateAppointmentResponse)(nil), // 2: appointment.v1.CreateAppointmentResponse
	(*GetAppointmentRequest)(nil),     // 3: appointment.v1.GetAppointmentRequest
	(*GetAppointmentResponse)(nil),    // 4: appointment.v1.GetAppointmentResponse
	(*ListAppointmentsRequest)(nil),   // 5: appointment.v1.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),  // 6: appointment.v1.ListAppointmentsResponse
	(*UpdateAppointmentRequest)(nil),  // 7: appointment.v1.UpdateAppointmentRequest
	(*UpdateAppointmentResponse)(nil), // 8: appointment.v1.UpdateAppointmentResponse
	(*CancelAppointmentRequest)(nil),  // 9: appointment.v1.CancelAppointmentRequest
	(*CancelAppointmentResponse)(nil), // 10: appointment.v1.CancelAppointmentResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_appointment_v1_appointment_proto_depIdxs = []int32{
	11, // 0: appointment.v1.Appointment.start:type_name -> google.protobuf.Timestamp
	11, // 1: appointment.v1.Appointment.end:type_name -> google.protobuf.Timestamp
	0,  // 2: appointment.v1.CreateAppointmentRequest.appointment:type_name -> appointment.v1.Appointment
	0,  // 3: appointment.v1.CreateAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	0,  // 4: appointment.v1.GetAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	0,  // 5: appointment.v1.ListAppointmentsResponse.appointments:type_name -> appointment.v1.Appointment
	0,  // 6: appointment.v1.UpdateAppointmentRequest.appointment:type_name -> appointment.v1.Appointment
	0,  // 7: appointment.v1.UpdateAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	0,  // 8: appointment.v1.CancelAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	1,  // 9: appointment.v1.AppointmentService.CreateAppointment:input_type -> appointment.v1.CreateAppointmentRequest
	3,  // 10: appointment.v1.AppointmentService.GetAppointment:input_type -> appointment.v1.GetAppointmentRequest
	5,  // 11: appointment.v1.AppointmentService.ListAppointments:input_type -> appointment.v1.ListAppointmentsRequest
	7,  // 12: appointment.v1.AppointmentService.UpdateAppointment:input_type -> appointment.v1.UpdateAppointmentRequest
	9,  // 13: appointment.v1.AppointmentService.CancelAppointment:input_type -> appointment.v1.CancelAppointmentRequest
	2,  // 14: appointment.v1.AppointmentService.CreateAppointment:output_type -> appointment.v1.CreateAppointmentResponse
	4,  // 15: appointment.v1.AppointmentService.GetAppointment:output_type -> appointment.v1.GetAppointmentResponse
	6,  // 16: appointment.v1.AppointmentService.ListAppointments:output_type -> appointment.v1.ListAppointmentsResponse
	8,  // 17: appointment.v1.AppointmentService.UpdateAppointment:output_type -> appointment.v1.UpdateAppointmentResponse
	10, // 18: appointment.v1.AppointmentService.CancelAppointment:output_type -> appointment.v1.CancelAppointmentResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_appointment_v1_appointment_proto_init() }
func file_appointment_v1_appointment_proto_init() {
	if File_appointment_v1_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appointment_v1_appointment_proto_rawDesc), len(file_appointment_v1_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_v1_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_v1_appointment_proto_depIdxs,
		MessageInfos:      file_appointment_v1_appointment_proto_msgTypes,
	}.Build()
	File_appointment_v1_appointment_proto = out.File
	file_appointment_v1_appointment_proto_goTypes = nil
	file_appointment_v1_appointment_proto_depIdxs = nil
}
