// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: observation/v1/observation.proto

package observationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Observation represents a lab result or clinical observation
type Observation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // registered, preliminary, final, amended, cancelled, entered-in-error, unknown
	PatientId          string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	EffectiveDatetime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effective_datetime,json=effectiveDatetime,proto3" json:"effective_datetime,omitempty"`
	Issued             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued,proto3" json:"issued,omitempty"`
	Code               string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	CodeSystem         string                 `protobuf:"bytes,7,opt,name=code_system,json=codeSystem,proto3" json:"code_system,omitempty"`
	ValueQuantityValue string                 `protobuf:"bytes,8,opt,name=value_quantity_value,json=valueQuantityValue,proto3" json:"value_quantity_value,omitempty"`
	ValueQuantityUnit  string                 `protobuf:"bytes,9,opt,name=value_quantity_unit,json=valueQuantityUnit,proto3" json:"value_quantity_unit,omitempty"`
	ValueString        string                 `protobuf:"bytes,10,opt,name=value_string,json=valueString,proto3" json:"value_string,omitempty"`
	Category           []string               `protobuf:"bytes,11,rep,name=category,proto3" json:"category,omitempty"`
	Interpretation     string                 `protobuf:"bytes,12,opt,name=interpretation,proto3" json:"interpretation,omitempty"`
	ReferenceRangeLow  string                 `protobuf:"bytes,13,opt,name=reference_range_low,json=referenceRangeLow,proto3" json:"reference_range_low,omitempty"`
	ReferenceRangeHigh string                 `protobuf:"bytes,14,opt,name=reference_range_high,json=referenceRangeHigh,proto3" json:"reference_range_high,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_observation_v1_observation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{0}
}

func (x *Observation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Observation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Observation) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Observation) GetEffectiveDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveDatetime
	}
	return nil
}

func (x *Observation) GetIssued() *timestamppb.Timestamp {
	if x != nil {
		return x.Issued
	}
	return nil
}

func (x *Observation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Observation) GetCodeSystem() string {
	if x != nil {
		return x.CodeSystem
	}
	return ""
}

func (x *Observation) GetValueQuantityValue() string {
	if x != nil {
		return x.ValueQuantityValue
	}
	return ""
}

func (x *Observation) GetValueQuantityUnit() string {
	if x != nil {
		return x.ValueQuantityUnit
	}
	return ""
}

func (x *Observation) GetValueString() string {
	if x != nil {
		return x.ValueString
	}
	return ""
}

func (x *Observation) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Observation) GetInterpretation() string {
	if x != nil {
		return x.Interpretation
	}
	return ""
}

func (x *Observation) GetReferenceRangeLow() string {
	if x != nil {
		return x.ReferenceRangeLow
	}
	return ""
}

func (x *Observation) GetReferenceRangeHigh() string {
	if x != nil {
		return x.ReferenceRangeHigh
	}
	return ""
}

func (x *Observation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Observation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateObservationRequest represents a request to create an observation
type CreateObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationRequest) Reset() {
	*x = CreateObservationRequest{}
	mi := &file_observation_v1_observation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationRequest) ProtoMessage() {}

func (x *CreateObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationRequest.ProtoReflect.Descriptor instead.
func (*CreateObservationRequest) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateObservationRequest) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

// CreateObservationResponse represents a response from creating an observation
type CreateObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationResponse) Reset() {
	*x = CreateObservationResponse{}
	mi := &file_observation_v1_observation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationResponse) ProtoMessage() {}

func (x *CreateObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationResponse.ProtoReflect.Descriptor instead.
func (*CreateObservationResponse) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateObservationResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

// GetObservationRequest represents a request to get an observation
type GetObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationRequest) Reset() {
	*x = GetObservationRequest{}
	mi := &file_observation_v1_observation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationRequest) ProtoMessage() {}

func (x *GetObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationRequest.ProtoReflect.Descriptor instead.
func (*GetObservationRequest) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{3}
}

func (x *GetObservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetObservationResponse represents a response from getting an observation
type GetObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationResponse) Reset() {
	*x = GetObservationResponse{}
	mi := &file_observation_v1_observation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationResponse) ProtoMessage() {}

func (x *GetObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationResponse.ProtoReflect.Descriptor instead.
func (*GetObservationResponse) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{4}
}

func (x *GetObservationResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

// ListObservationsRequest represents a request to list observations
type ListObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // Required: filter by patient
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObservationsRequest) Reset() {
	*x = ListObservationsRequest{}
	mi := &file_observation_v1_observation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObservationsRequest) ProtoMessage() {}

func (x *ListObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObservationsRequest.ProtoReflect.Descriptor instead.
func (*ListObservationsRequest) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{5}
}

func (x *ListObservationsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListObservationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListObservationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListObservationsResponse represents a response from listing observations
type ListObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObservationsResponse) Reset() {
	*x = ListObservationsResponse{}
	mi := &file_observation_v1_observation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObservationsResponse) ProtoMessage() {}

func (x *ListObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObservationsResponse.ProtoReflect.Descriptor instead.
func (*ListObservationsResponse) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{6}
}

func (x *ListObservationsResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *ListObservationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateObservationStatusRequest represents a request to update observation status
type UpdateObservationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObservationStatusRequest) Reset() {
	*x = UpdateObservationStatusRequest{}
	mi := &file_observation_v1_observation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObservationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObservationStatusRequest) ProtoMessage() {}

func (x *UpdateObservationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObservationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateObservationStatusRequest) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateObservationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateObservationStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateObservationStatusResponse represents a response from updating observation status
type UpdateObservationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObservationStatusResponse) Reset() {
	*x = UpdateObservationStatusResponse{}
	mi := &file_observation_v1_observation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObservationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObservationStatusResponse) ProtoMessage() {}

func (x *UpdateObservationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObservationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateObservationStatusResponse) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateObservationStatusResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

// GenerateLabObservationsRequest represents a request to generate lab observations
type GenerateLabObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // Required: patient ID to generate observations for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLabObservationsRequest) Reset() {
	*x = GenerateLabObservationsRequest{}
	mi := &file_observation_v1_observation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLabObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLabObservationsRequest) ProtoMessage() {}

func (x *GenerateLabObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLabObservationsRequest.ProtoReflect.Descriptor instead.
func (*GenerateLabObservationsRequest) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateLabObservationsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

// GenerateLabObservationsResponse represents a response from generating lab observations
type GenerateLabObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"` // The generated observations
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`              // Number of observations generated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLabObservationsResponse) Reset() {
	*x = GenerateLabObservationsResponse{}
	mi := &file_observation_v1_observation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLabObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLabObservationsResponse) ProtoMessage() {}

func (x *GenerateLabObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observation_v1_observation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLabObservationsResponse.ProtoReflect.Descriptor instead.
func (*GenerateLabObservationsResponse) Descriptor() ([]byte, []int) {
	return file_observation_v1_observation_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateLabObservationsResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *GenerateLabObservationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_observation_v1_observation_proto protoreflect.FileDescriptor

const file_observation_v1_observation_proto_rawDesc = "" +
	"\n" +
	" observation/v1/observation.proto\x12\x0eobservation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x05\n" +
	"\vObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12I\n" +
	"\x12effective_datetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11effectiveDatetime\x122\n" +
	"\x06issued\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06issued\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x1f\n" +
	"\vcode_system\x18\a \x01(\tR\n" +
	"codeSystem\x120\n" +
	"\x14value_quantity_value\x18\b \x01(\tR\x12valueQuantityValue\x12.\n" +
	"\x13value_quantity_unit\x18\t \x01(\tR\x11valueQuantityUnit\x12!\n" +
	"\fvalue_string\x18\n" +
	" \x01(\tR\vvalueString\x12\x1a\n" +
	"\bcategory\x18\v \x03(\tR\bcategory\x12&\n" +
	"\x0einterpretation\x18\f \x01(\tR\x0einterpretation\x12.\n" +
	"\x13reference_range_low\x18\r \x01(\tR\x11referenceRangeLow\x120\n" +
	"\x14reference_range_high\x18\x0e \x01(\tR\x12referenceRangeHigh\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x18CreateObservationRequest\x12=\n" +
	"\vobservation\x18\x01 \x01(\v2\x1b.observation.v1.ObservationR\vobservation\"Z\n" +
	"\x19CreateObservationResponse\x12=\n" +
	"\vobservation\x18\x01 \x01(\v2\x1b.observation.v1.ObservationR\vobservation\"'\n" +
	"\x15GetObservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x16GetObservationResponse\x12=\n" +
	"\vobservation\x18\x01 \x01(\v2\x1b.observation.v1.ObservationR\vobservation\"t\n" +
	"\x17ListObservationsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x18ListObservationsResponse\x12?\n" +
	"\fobservations\x18\x01 \x03(\v2\x1b.observation.v1.ObservationR\fobservations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"H\n" +
	"\x1eUpdateObservationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"`\n" +
	"\x1fUpdateObservationStatusResponse\x12=\n" +
	"\vobservation\x18\x01 \x01(\v2\x1b.observation.v1.ObservationR\vobservation\"?\n" +
	"\x1eGenerateLabObservationsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"x\n" +
	"\x1fGenerateLabObservationsResponse\x12?\n" +
	"\fobservations\x18\x01 \x03(\v2\x1b.observation.v1.ObservationR\fobservations\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xbe\x04\n" +
	"\x12ObservationService\x12h\n" +
	"\x11CreateObservation\x12(.observation.v1.CreateObservationRequest\x1a).observation.v1.CreateObservationResponse\x12_\n" +
	"\x0eGetObservation\x12%.observation.v1.GetObservationRequest\x1a&.observation.v1.GetObservationResponse\x12e\n" +
	"\x10ListObservations\x12'.observation.v1.ListObservationsRequest\x1a(.observation.v1.ListObservationsResponse\x12z\n" +
	"\x17UpdateObservationStatus\x12..observation.v1.UpdateObservationStatusRequest\x1a/.observation.v1.UpdateObservationStatusResponse\x12z\n" +
	"\x17GenerateLabObservations\x12..observation.v1.GenerateLabObservationsRequest\x1a/.observation.v1.GenerateLabObservationsResponseB\xcd\x01\n" +
	"\x12com.observation.v1B\x10ObservationProtoP\x01ZLgithub.com/Sotiris-Bekiaris/careflow-mini/proto/observation/v1;observationv1\xa2\x02\x03OXX\xaa\x02\x0eObservation.V1\xca\x02\x0eObservation\\V1\xe2\x02\x1aObservation\\V1\\GPBMetadata\xea\x02\x0fObservation::V1b\x06proto3"

var (
	file_observation_v1_observation_proto_rawDescOnce sync.Once
	file_observation_v1_observation_proto_rawDescData []byte
)

func file_observation_v1_observation_proto_rawDescGZIP() []byte {
	file_observation_v1_observation_proto_rawDescOnce.Do(func() {
		file_observation_v1_observation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observation_v1_observation_proto_rawDesc), len(file_observation_v1_observation_proto_rawDesc)))
	})
	return file_observation_v1_observation_proto_rawDescData
}

var file_observation_v1_observation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_observation_v1_observation_proto_goTypes = []any{
	(*Observation)(nil),                     // 0: observation.v1.Observation
	(*CreateObservationRequest)(nil),        // 1: observation.v1.CreateObservationRequest
	(*CreateObservationResponse)(nil),       // 2: observation.v1.CreateObservationResponse
	(*GetObservationRequest)(nil),           // 3: observation.v1.GetObservationRequest
	(*GetObservationResponse)(nil),          // 4: observation.v1.GetObservationResponse
	(*ListObservationsRequest)(nil),         // 5: observation.v1.ListObservationsRequest
	(*ListObservationsResponse)(nil),        // 6: observation.v1.ListObservationsResponse
	(*UpdateObservationStatusRequest)(nil),  // 7: observation.v1.UpdateObservationStatusRequest
	(*UpdateObservationStatusResponse)(nil), // 8: observation.v1.UpdateObservationStatusResponse
	(*GenerateLabObservationsRequest)(nil),  // 9: observation.v1.GenerateLabObservationsRequest
	(*GenerateLabObservationsResponse)(nil), // 10: observation.v1.GenerateLabObservationsResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_observation_v1_observation_proto_depIdxs = []int32{
	11, // 0: observation.v1.Observation.effective_datetime:type_name -> google.protobuf.Timestamp
	11, // 1: observation.v1.Observation.issued:type_name -> google.protobuf.Timestamp
	11, // 2: observation.v1.Observation.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: observation.v1.Observation.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: observation.v1.CreateObservationRequest.observation:type_name -> observation.v1.Observation
	0,  // 5: observation.v1.CreateObservationResponse.observation:type_name -> observation.v1.Observation
	0,  // 6: observation.v1.GetObservationResponse.observation:type_name -> observation.v1.Observation
	0,  // 7: observation.v1.ListObservationsResponse.observations:type_name -> observation.v1.Observation
	0,  // 8: observation.v1.UpdateObservationStatusResponse.observation:type_name -> observation.v1.Observation
	0,  // 9: observation.v1.GenerateLabObservationsResponse.observations:type_name -> observation.v1.Observation
	1,  // 10: observation.v1.ObservationService.CreateObservation:input_type -> observation.v1.CreateObservationRequest
	3,  // 11: observation.v1.ObservationService.GetObservation:input_type -> observation.v1.GetObservationRequest
	5,  // 12: observation.v1.ObservationService.ListObservations:input_type -> observation.v1.ListObservationsRequest
	7,  // 13: observation.v1.ObservationService.UpdateObservationStatus:input_type -> observation.v1.UpdateObservationStatusRequest
	9,  // 14: observation.v1.ObservationService.GenerateLabObservations:input_type -> observation.v1.GenerateLabObservationsRequest
	2,  // 15: observation.v1.ObservationService.CreateObservation:output_type -> observation.v1.CreateObservationResponse
	4,  // 16: observation.v1.ObservationService.GetObservation:output_type -> observation.v1.GetObservationResponse
	6,  // 17: observation.v1.ObservationService.ListObservations:output_type -> observation.v1.ListObservationsResponse
	8,  // 18: observation.v1.ObservationService.UpdateObservationStatus:output_type -> observation.v1.UpdateObservationStatusResponse
	10, // 19: observation.v1.ObservationService.GenerateLabObservations:output_type -> observation.v1.GenerateLabObservationsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_observation_v1_observation_proto_init() }
func file_observation_v1_observation_proto_init() {
	if File_observation_v1_observation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observation_v1_observation_proto_rawDesc), len(file_observation_v1_observation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observation_v1_observation_proto_goTypes,
		DependencyIndexes: file_observation_v1_observation_proto_depIdxs,
		MessageInfos:      file_observation_v1_observation_proto_msgTypes,
	}.Build()
	File_observation_v1_observation_proto = out.File
	file_observation_v1_observation_proto_goTypes = nil
	file_observation_v1_observation_proto_depIdxs = nil
}
