// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: observation/v1/observation.proto

package observationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservationService_CreateObservation_FullMethodName       = "/observation.v1.ObservationService/CreateObservation"
	ObservationService_GetObservation_FullMethodName          = "/observation.v1.ObservationService/GetObservation"
	ObservationService_ListObservations_FullMethodName        = "/observation.v1.ObservationService/ListObservations"
	ObservationService_UpdateObservationStatus_FullMethodName = "/observation.v1.ObservationService/UpdateObservationStatus"
)

// ObservationServiceClient is the client API for ObservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObservationService handles observation/lab result operations
type ObservationServiceClient interface {
	// CreateObservation creates a new observation
	CreateObservation(ctx context.Context, in *CreateObservationRequest, opts ...grpc.CallOption) (*CreateObservationResponse, error)
	// GetObservation retrieves an observation by ID
	GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error)
	// ListObservations lists observations for a patient
	ListObservations(ctx context.Context, in *ListObservationsRequest, opts ...grpc.CallOption) (*ListObservationsResponse, error)
	// UpdateObservationStatus updates the status of an observation
	UpdateObservationStatus(ctx context.Context, in *UpdateObservationStatusRequest, opts ...grpc.CallOption) (*UpdateObservationStatusResponse, error)
}

type observationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObservationServiceClient(cc grpc.ClientConnInterface) ObservationServiceClient {
	return &observationServiceClient{cc}
}

func (c *observationServiceClient) CreateObservation(ctx context.Context, in *CreateObservationRequest, opts ...grpc.CallOption) (*CreateObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateObservationResponse)
	err := c.cc.Invoke(ctx, ObservationService_CreateObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationServiceClient) GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObservationResponse)
	err := c.cc.Invoke(ctx, ObservationService_GetObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationServiceClient) ListObservations(ctx context.Context, in *ListObservationsRequest, opts ...grpc.CallOption) (*ListObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObservationsResponse)
	err := c.cc.Invoke(ctx, ObservationService_ListObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationServiceClient) UpdateObservationStatus(ctx context.Context, in *UpdateObservationStatusRequest, opts ...grpc.CallOption) (*UpdateObservationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateObservationStatusResponse)
	err := c.cc.Invoke(ctx, ObservationService_UpdateObservationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservationServiceServer is the server API for ObservationService service.
// All implementations must embed UnimplementedObservationServiceServer
// for forward compatibility.
//
// ObservationService handles observation/lab result operations
type ObservationServiceServer interface {
	// CreateObservation creates a new observation
	CreateObservation(context.Context, *CreateObservationRequest) (*CreateObservationResponse, error)
	// GetObservation retrieves an observation by ID
	GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error)
	// ListObservations lists observations for a patient
	ListObservations(context.Context, *ListObservationsRequest) (*ListObservationsResponse, error)
	// UpdateObservationStatus updates the status of an observation
	UpdateObservationStatus(context.Context, *UpdateObservationStatusRequest) (*UpdateObservationStatusResponse, error)
	mustEmbedUnimplementedObservationServiceServer()
}

// UnimplementedObservationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservationServiceServer struct{}

func (UnimplementedObservationServiceServer) CreateObservation(context.Context, *CreateObservationRequest) (*CreateObservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObservation not implemented")
}
func (UnimplementedObservationServiceServer) GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObservation not implemented")
}
func (UnimplementedObservationServiceServer) ListObservations(context.Context, *ListObservationsRequest) (*ListObservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObservations not implemented")
}
func (UnimplementedObservationServiceServer) UpdateObservationStatus(context.Context, *UpdateObservationStatusRequest) (*UpdateObservationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateObservationStatus not implemented")
}
func (UnimplementedObservationServiceServer) mustEmbedUnimplementedObservationServiceServer() {}
func (UnimplementedObservationServiceServer) testEmbeddedByValue()                            {}

// UnsafeObservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservationServiceServer will
// result in compilation errors.
type UnsafeObservationServiceServer interface {
	mustEmbedUnimplementedObservationServiceServer()
}

func RegisterObservationServiceServer(s grpc.ServiceRegistrar, srv ObservationServiceServer) {
	// If the following call pancis, it indicates UnimplementedObservationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservationService_ServiceDesc, srv)
}

func _ObservationService_CreateObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).CreateObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_CreateObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).CreateObservation(ctx, req.(*CreateObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationService_GetObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).GetObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_GetObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).GetObservation(ctx, req.(*GetObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationService_ListObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).ListObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_ListObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).ListObservations(ctx, req.(*ListObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationService_UpdateObservationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObservationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationServiceServer).UpdateObservationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationService_UpdateObservationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationServiceServer).UpdateObservationStatus(ctx, req.(*UpdateObservationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservationService_ServiceDesc is the grpc.ServiceDesc for ObservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "observation.v1.ObservationService",
	HandlerType: (*ObservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObservation",
			Handler:    _ObservationService_CreateObservation_Handler,
		},
		{
			MethodName: "GetObservation",
			Handler:    _ObservationService_GetObservation_Handler,
		},
		{
			MethodName: "ListObservations",
			Handler:    _ObservationService_ListObservations_Handler,
		},
		{
			MethodName: "UpdateObservationStatus",
			Handler:    _ObservationService_UpdateObservationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "observation/v1/observation.proto",
}
